project:
  type: website
  output-dir: ../docs/rajasthan

website:
  title: "2023 Indian Elections Dashboard - Rajasthan"
  navbar:
    left:
      - href: spending.qmd
        text: Spending
      - sidebar:targeting
      - href: about.qmd
        text: About
      - href: https://favstats.github.io/IN2023/mp/spending.html
        text: Madhya Pradesh
    right:
      - icon: github
        href: https://github.com/favstats/IN2023
  sidebar:
    - id: ""
    - id: targeting
      title: "Targeting"
      style: "docked"
      collapse-level: 2
      contents:
        - targeting.qmd
        - detailed.qmd
        - location.qmd
        - demographics.qmd

format:
  html:
    theme:
      - cosmo
      - custom.scss
    mainfont: acumin-pro-semi-condensed, helvetica, arial, sans-serif
    fontsize: 1.2em